# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Devices_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_device(object):
    def setupUi(self, MainWindow_device):
        MainWindow_device.setObjectName("MainWindow_device")
        MainWindow_device.resize(767, 197)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actionicons/device.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_device.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow_device)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow_device.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_device)
        self.statusbar.setObjectName("statusbar")
        MainWindow_device.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_device)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_device)

    def retranslateUi(self, MainWindow_device):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_device.setWindowTitle(_translate("MainWindow_device", "Devices Config"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow_device", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow_device", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_device", "Devices Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_device", "Type of Connection"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_device", "Address"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_ok.setText(_translate("MainWindow_device", "OK"))
        self.pushButton_cancel.setText(_translate("MainWindow_device", "Cancel"))
from image import icons_rc
