# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_caseparms.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_caseparms(object):
    def setupUi(self, win_caseparms):
        win_caseparms.setObjectName("win_caseparms")
        win_caseparms.resize(931, 618)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actionicons/new_seq_64px.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_caseparms.setWindowIcon(icon)
        win_caseparms.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(win_caseparms)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        win_caseparms.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(win_caseparms)
        self.statusbar.setObjectName("statusbar")
        win_caseparms.setStatusBar(self.statusbar)

        self.retranslateUi(win_caseparms)
        QtCore.QMetaObject.connectSlotsByName(win_caseparms)

    def retranslateUi(self, win_caseparms):
        _translate = QtCore.QCoreApplication.translate
        win_caseparms.setWindowTitle(_translate("win_caseparms", "Edit test item parameters"))
        self.label.setText(_translate("win_caseparms", "TextLabel"))
        self.pushButton_ok.setText(_translate("win_caseparms", "OK"))
        self.pushButton_cancel.setText(_translate("win_caseparms", "Cancel"))
from image import icons_rc
