# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_channel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_Channel(object):
    def setupUi(self, win_Channel):
        win_Channel.setObjectName("win_Channel")
        win_Channel.resize(1294, 617)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actionicons/arrow_down_up_64px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_Channel.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(win_Channel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        win_Channel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(win_Channel)
        self.statusbar.setObjectName("statusbar")
        win_Channel.setStatusBar(self.statusbar)

        self.retranslateUi(win_Channel)
        QtCore.QMetaObject.connectSlotsByName(win_Channel)

    def retranslateUi(self, win_Channel):
        _translate = QtCore.QCoreApplication.translate
        win_Channel.setWindowTitle(_translate("win_Channel", "NR Channel Config"))
        self.pushButton_ok.setText(_translate("win_Channel", "OK"))
        self.pushButton_cancel.setText(_translate("win_Channel", "Cancel"))
from image import icons_rc
